version: '3'

services:
  web:
    container_name: "orbit"
    build: .
    volumes:
      - .:/orbit
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: "service_healthy"
        restart: true
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=localhost
    labels:
      description: "Postgresql Database"
      service: "postgresql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


volumes:
  postgres_data: